# Exported from Render on 2024-12-19T13:43:38Z
services:
- type: web
  name: ModConnect
  runtime: docker
  repo: https://github.com/gaurabn1/ModConnect
  plan: free
  envVars:
  - key: False
    sync: false
  - key: gaurabneupane8969@gmail.com
    sync: false
  - key: zdiiohjtdlxiakpb
    sync: false
  - key: tu!vjsmkj@aw1im$--fy0tn_d&8bbe+p%uxf4h=)k29e$8q(=k
    sync: false
  - key: postgresql://modconnect_user:lUtWraGM74HT2mKcY43xmhocFcvpkPVX@dpg-cti1atl2ng1s73edcb20-a.singapore-postgres.render.com/modconnect_db   
    sync: false
  region: singapore
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
