# Exported from Render on 2024-12-19T13:43:38Z
services:
- type: web
  name: ModConnect
  runtime: docker
  repo: https://github.com/gaurabn1/ModConnect.
  plan: free
  envVars:
  - key: DEBUG
    sync: false
  - key: EMAIL_HOST_USER
    sync: false
  - key: EMAIL_HOST_PASSWORD
    sync: false
  - key: POSTGRES_PORT
    sync: false
  - key: POSTGRES_PASSWORD
    sync: false
  - key: POSTGRES_USER
    sync: false
  - key: POSTGRES_HOST
    sync: false
  - key: POSTGRES_DB
    sync: false
  - key: SECRET_KEY
    sync: false
  region: singapore
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
